import { useState } from 'react'
import { SectionHead, SpeakerNote, CopyButton } from '../components/Primitives'
import { zqlSteps, zqlProtects, zqlDoesNot, maturity, failureModes, operatingModel } from '../data/content'

const ZQL_STATEMENT =
  'ZQL applies to web search queries generated by Microsoft 365 Copilot, Copilot Chat, and the Researcher agent when operating within the Microsoft 365 Copilot service. In this GCC High environment, users access through the enterprise tenant, so ZQL applies. ZQL does not eliminate the boundary crossing or the approval requirement — it governs what happens after the query reaches Bing.'

export function Zql() {
  const [step, setStep] = useState(0)
  const sideLabel = (s: string) => (s === 'in' ? 'Inside boundary' : s === 'cross' ? 'Boundary crossing' : 'Commercial Bing')
  return (
    <>
      <SectionHead num="05" title="ZQL — Zero Query Logging">
        What happens when web grounding is ON. Click "Step through" to walk it during the meeting.
      </SectionHead>
      <SpeakerNote>
        The key point: a SHORT DERIVED QUERY goes to Bing — not the prompt, not tenant data. ZQL means Bing
        discards everything after processing. It is a retention control, not a boundary elimination — that is
        why approval is still required. ZQL applies because users are in the M365 service context (your
        enterprise tenant), not consumer Copilot.
      </SpeakerNote>
      <div style={{ display: 'flex', gap: 10, marginBottom: 10 }}>
        <button className="btn btn-primary" onClick={() => setStep((s) => Math.min(s + 1, (zqlSteps as any[]).length))}>Step through ▸</button>
        <button className="btn" onClick={() => setStep(0)}>Reset</button>
        <button className="btn" onClick={() => setStep((zqlSteps as any[]).length)}>Show all</button>
      </div>
      <div className="card"><div className="zql-flow">
        {(zqlSteps as any[]).map((s, i) => (
          <div key={i} className={`zql-step ${s.side}${i < step ? ' shown' : ''}`}>
            <div className="zs-num">{s.n}</div>
            <div className="zs-body">
              <div className="zs-t">{s.t}</div>
              <div className="zs-d">{s.d}</div>
              <span className={`zs-side ${s.side}`}>{sideLabel(s.side)}</span>
            </div>
          </div>
        ))}
      </div></div>
      <div className="grid grid-2" style={{ marginTop: 16 }}>
        <div className="card"><div className="card-h" style={{ color: 'var(--green)' }}>What ZQL protects</div>
          <ul className="pd-list pd-done">{(zqlProtects as string[]).map((x, i) => <li key={i}>{x}</li>)}</ul></div>
        <div className="card"><div className="card-h" style={{ color: 'var(--amber)' }}>What ZQL does NOT do</div>
          <ul className="pd-list">{(zqlDoesNot as string[]).map((x, i) => <li key={i} style={{ color: 'var(--slate)' }}>{x}</li>)}</ul></div>
      </div>
      <div className="statement">
        <div style={{ float: 'right' }}><CopyButton text={ZQL_STATEMENT} /></div>
        <div className="st-label">Defensible statement</div>
        {ZQL_STATEMENT}
      </div>
    </>
  )
}

export function Scale() {
  const [layer, setLayer] = useState<number | null>(null)
  return (
    <>
      <SectionHead num="11" title="AI Strategy at Scale">
        How federal organizations scale AI — and the failure modes that stop them.
      </SectionHead>
      <SpeakerNote>
        This makes the meeting bigger than Copilot. The pilot is the first build of a reusable operating model —
        approval workflows, access controls, audit posture that every future AI use case inherits. Name the
        failure modes if they are slow-walking: pilot hell, governance bottleneck. "Organizations that succeed
        don't deploy AI faster — they industrialize AI delivery."
      </SpeakerNote>
      <div className="card-h">Maturity model</div>
      <div className="maturity">
        {(maturity as any[]).map((m, i) => (
          <div className="mat-step" key={i}>
            <div className="ms-level">{m.level}</div>
            <div className="ms-desc">{m.desc}</div>
          </div>
        ))}
      </div>
      <div className="card" style={{ marginTop: 18 }}>
        <div className="card-h">The four-layer operating model</div>
        <p style={{ fontSize: 12, color: 'var(--gray)', margin: '4px 0 10px' }}>Click any layer to expand the detail.</p>
        <div className="grid grid-2" style={{ marginTop: 6 }}>
          {(operatingModel as any[]).map((x, i) => {
            const open = layer === i
            return (
              <div key={i} onClick={() => setLayer(open ? null : i)}
                style={{ background: open ? 'var(--sky)' : 'var(--ltgray)', borderRadius: 8, padding: 12, cursor: 'pointer', border: `1px solid ${open ? 'var(--blue)' : 'transparent'}`, transition: 'all .15s' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--navy)' }}>{x.t}</div>
                  <span style={{ color: 'var(--blue)', fontSize: 13 }}>{open ? '−' : '+'}</span>
                </div>
                <div style={{ fontSize: 12, color: 'var(--gray)', marginTop: 4 }}>{x.short}</div>
                {open && (
                  <div style={{ marginTop: 10, paddingTop: 10, borderTop: '1px solid var(--border)' }}>
                    <div style={{ fontSize: 12.5, color: 'var(--slate)', lineHeight: 1.6 }}>{x.detail}</div>
                    <div style={{ fontSize: 10, fontWeight: 800, color: 'var(--blue)', textTransform: 'uppercase', marginTop: 8 }}>What good looks like</div>
                    <ul className="pd-list pd-done" style={{ fontSize: 12, marginTop: 4 }}>{x.signals.map((s: string, j: number) => <li key={j}>{s}</li>)}</ul>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>
      <div className="card-h" style={{ marginTop: 18 }}>Failure modes to avoid</div>
      <div className="grid grid-2">
        {(failureModes as any[]).map((f, i) => (
          <div className="card" key={i} style={{ borderLeft: '4px solid var(--red)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--red)' }}>{f.t}</div>
            <div style={{ fontSize: 12.5, color: 'var(--gray)', marginTop: 4 }}>{f.d}</div>
          </div>
        ))}
      </div>
    </>
  )
}
